# Generated by Django 2.1.4 on 2018-12-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosearchengine', '0002_auto_20181124_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvertedIndexLookup',
        ),
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
