# Generated by Django 2.1.4 on 2018-12-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosearchengine', '0003_auto_20181204_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_text',
            field=models.TextField(null=True),
        ),
    ]
