# Generated by Django 2.1.4 on 2018-12-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosearchengine', '0004_auto_20181204_0342'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gc_uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
