version: '3'
services:
  db:
    image: postgres:10.0
    restart: always
    environment:
      POSTGRES_DB: videosearch
      POSTGRES_USER: videosearch
      POSTGRES_PASSWORD: securepass

  web:
    build: ./cs410videosearchengine/
    restart: always
    command: gunicorn --reload -w 3 -b :8000 --timeout 600 cs410videosearchengine.wsgi:application
    volumes:
      - ./cs410videosearchengine/:/src
      - /home/ubuntu/.aws/:/root/.aws/
    depends_on:
      - db

  nginx:
    restart: always
    build:
      ./frontend/.
    ports:
        - 0.0.0.0:80:80

  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
     restart: always
     ulimits:
       memlock: -1
     ports:
       - 9200:9200
       - 9300:9300
     volumes:
       - ./esdata:/usr/share/elasticsearch/data
     environment:
       ES_JAVA_OPTS: "-Xms500m -Xmx500m"

  redis:
    image: 'redis:latest'
    command: redis-server

  worker:
      build: ./cs410videosearchengine/
      restart: always
      volumes:
        - ./cs410videosearchengine/:/src
        - /home/ubuntu/.aws/:/root/.aws/
      command: celery -A cs410videosearchengine worker -l info
      stdin_open: true
      tty: true

  beat: 
      build: ./cs410videosearchengine/
      restart: always
      volumes:
        - ./cs410videosearchengine/:/src
        - /home/ubuntu/.aws/:/root/.aws/
      command: celery -A cs410videosearchengine beat -l info
      stdin_open: true
      tty: true
