  - name: add docker apt key
    become: yes
    apt_key: 
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: add docker apt repository
    become: yes
    apt_repository: 
      state: present 
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} edge'

  - name: Install packages
    become: yes
    apt: 
      name: ['docker-ce', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip']
      update_cache: yes
      state: present

  - name: add user to docker group
    become: yes
    user: 
      name: "{{ ansible_user }}"
      group: docker

  - name: pip3 install docker-compose
    become: yes
    pip: 
      name: docker-compose
